name: imake
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.0.0
  built_value: ^8.0.6
  cached_network_image: ^3.1.0
  image_picker: ^0.8.3+2
  json_serializable: ^3.5.1
  mime_type: ^1.0.0
  rxdart: ^0.26.0
  sign_in_with_apple: ^2.5.4
  cupertino_icons: ^1.0.3
  smooth_page_indicator: ^0.2.3
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  intl: ^0.17.0
  google_fonts: ^2.1.0
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.4.0
  dash_chat: ^1.1.16
  flutter_calendar_week: ^2.0.0
  bottom_picker: ^1.0.1
  cell_calendar: ^0.5.0+1
  flutter_picker: ^2.0.2
  http: ^0.13.3
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.1

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/imakelogo.png'


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/images/imakelogo.png